### ISSUE TITLE
cfg80211 wireless extensions compatibility does not work properly

### ISSUE THREAD

**Issue by shandongtlb** [Re4son/android_kernel_oneplus_sm8150#1]
Hello, because iwconfig can not be used, I checked the "Network-->wireless-->cfg80211 wireless extensions compatibility" in the menuconfig of your kernel source, and found that the boot can not be started, what is the reason? thanks！

**Comment by kimocoder** [comment]
@Re4son tagged and bagged :100:

**Comment by shandongtlb** [comment]
I've solved it

Just set up nethunter_defconfig qca_cld driver


#
# Qualcomm Atheros CLD WLAN module
#
CONFIG_QCA_CLD_WLAN=y
CONFIG_QCACLD_WLAN_LFR3=y
CONFIG_PRIMA_WLAN_OKC=y
CONFIG_WLAN_FEATURE_11W=y
CONFIG_WLAN_FEATURE_LPSS=y
CONFIG_QCOM_VOWIFI_11R=y
CONFIG_QCACLD_FEATURE_NAN=y
CONFIG_WLAN_FEATURE_NAN_DATAPATH=y
CONFIG_QCACLD_FEATURE_GREEN_AP=y
# CONFIG_HELIUMPLUS is not set
CONFIG_QCOM_TDLS=y
CONFIG_QCOM_LTE_COEX=y
CONFIG_MPC_UT_FRAMEWORK=y
CONFIG_WLAN_OFFLOAD_PACKETS=y
CONFIG_WLAN_FASTPATH=y
CONFIG_WLAN_NAPI=y
# CONFIG_WLAN_NAPI_DEBUG is not set
CONFIG_WLAN_TX_FLOW_CONTROL_V2=y
CONFIG_WLAN_SYNC_TSF=y
CONFIG_LFR_SUBNET_DETECTION=y
CONFIG_MCC_TO_SCC_SWITCH=y
CONFIG_QCACLD_WLAN_LFR2=y
CONFIG_WLAN_FEATURE_DISA=y
CONFIG_WLAN_FEATURE_FIPS=y
CONFIG_WLAN_FEATURE_11AX=y
CONFIG_ICMP_DISABLE_PS=y
CONFIG_BUILD_TIMESTAMP=y
CONFIG_WLAN_FEATURE_FILS=y
CONFIG_NAN_CONVERGENCE=y
CONFIG_WLAN_OBJMGR_DEBUG=y
CONFIG_WLAN_FEATURE_DFS_OFFLOAD=y
CONFIG_WLAN_FEATURE_SARV1_TO_SARV2=y
# CONFIG_GOLDFISH is not set
# CONFIG_CHROME_PLATFORMS is not set

**Comment by Re4son** [comment]
Impressive work, thanks. How did you debug it?

**Comment by shandongtlb** [comment]
I compiled the driver into modules,and into aarch64-linux-android-4.9/bin run “./aarch64-linux-androidkernel-strip -g wlan.ko”,finally you should add insmod wlan.ko into init.rc
